import React, { useEffect } from 'react';
import { X, ShieldCheck, Eye, Lock, HelpCircle, Scale, MapPin } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { springSmooth, springSnappy } from '../motion-presets';

const pillars = [
  {
    icon: Scale,
    color: '#047857',
    bg: 'rgba(4,120,87,0.09)',
    title: '1. Fairness & Robustness',
    text: 'Evaluated across diverse backgrounds, uneven lighting, varied camera angles, and both pristine and wrinkled household packaging.',
  },
  {
    icon: Eye,
    color: '#2563eb',
    bg: 'rgba(37,99,235,0.09)',
    title: '2. Transparency & Explainability',
    text: 'Recommendations explicitly state they are generated by multimodal AI and provide visual reasoning explaining why a category was chosen.',
  },
  {
    icon: HelpCircle,
    color: '#d97706',
    bg: 'rgba(217,119,6,0.09)',
    title: '3. Uncertainty & Abstention',
    text: 'When presented with mixed waste or ambiguous objects, the AI abstains from guessing and advises separating materials before binning.',
  },
  {
    icon: Lock,
    color: '#6d28d9',
    bg: 'rgba(109,40,217,0.09)',
    title: '4. Privacy & Ephemeral Processing',
    text: 'Images are processed in-memory as ephemeral byte streams and never stored, indexed, or shared with third parties.',
  },
  {
    icon: MapPin,
    color: '#059669',
    bg: 'rgba(5,150,105,0.09)',
    title: '5. Local Rules & Context',
    text: 'Explicitly recognizes that waste bylaws differ regionally and instructs users to verify against local campus or municipal guidelines.',
  },
];

export default function ResponsibleAiModal({ isOpen, onClose }) {
  // Close on Escape
  useEffect(() => {
    const handleKey = (e) => { if (e.key === 'Escape') onClose(); };
    if (isOpen) window.addEventListener('keydown', handleKey);
    return () => window.removeEventListener('keydown', handleKey);
  }, [isOpen, onClose]);

  return (
    <AnimatePresence>
      {isOpen && (
        <>
          {/* Backdrop */}
          <motion.div
            className="modal-overlay"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.22 }}
            onClick={onClose}
            style={{ alignItems: 'flex-end' }}
          >
            {/* Sheet — slides up from bottom on mobile, scale+fade on desktop */}
            <motion.div
              onClick={(e) => e.stopPropagation()}
              initial={{ y: '100%', opacity: 0 }}
              animate={{ y: 0, opacity: 1 }}
              exit={{ y: '100%', opacity: 0 }}
              transition={springSmooth}
              drag="y"
              dragConstraints={{ top: 0 }}
              dragElastic={{ top: 0, bottom: 0.3 }}
              onDragEnd={(_, info) => {
                if (info.offset.y > 120) onClose();
              }}
              style={{
                background: 'var(--glass-lg-bg)',
                backdropFilter: 'var(--glass-lg-blur)',
                WebkitBackdropFilter: 'var(--glass-lg-blur)',
                border: 'var(--glass-lg-border)',
                borderRadius: 'var(--radius-xl) var(--radius-xl) 0 0',
                boxShadow: 'var(--glass-lg-shadow)',
                width: '100%',
                maxWidth: '640px',
                maxHeight: '90vh',
                overflowY: 'auto',
                padding: '0',
                cursor: 'grab',
              }}
            >
              {/* Drag handle bar */}
              <div style={{ display: 'flex', justifyContent: 'center', paddingTop: '0.75rem', paddingBottom: '0.25rem' }}>
                <div style={{
                  width: '40px',
                  height: '5px',
                  borderRadius: 'var(--radius-full)',
                  background: 'rgba(100,116,139,0.30)',
                }} />
              </div>

              <div style={{ padding: '1.25rem 2rem 2rem', cursor: 'default' }}>
                {/* Header */}
                <div style={{
                  display: 'flex',
                  justifyContent: 'space-between',
                  alignItems: 'center',
                  marginBottom: '1.25rem',
                  paddingBottom: '1rem',
                  borderBottom: '1px solid rgba(226,232,240,0.5)',
                }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem' }}>
                    <div style={{
                      background: 'rgba(4,120,87,0.12)',
                      borderRadius: '10px',
                      width: '38px',
                      height: '38px',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                    }}>
                      <ShieldCheck size={20} color="var(--color-emerald)" />
                    </div>
                    <h2 style={{ fontSize: '1.3rem', color: 'var(--color-forest)', margin: 0 }}>
                      Responsible AI Framework
                    </h2>
                  </div>
                  <motion.button
                    onClick={onClose}
                    className="btn-icon"
                    style={{ flexShrink: 0 }}
                    whileTap={{ scale: 0.88, transition: springSnappy }}
                  >
                    <X size={17} />
                  </motion.button>
                </div>

                <p style={{ fontSize: '0.875rem', color: 'var(--color-muted)', marginBottom: '1.5rem', lineHeight: 1.6 }}>
                  In accordance with the{' '}
                  <strong>1M1B AI for Sustainability Virtual Internship (IBM SkillsBuild / AICTE)</strong>{' '}
                  guidelines, EcoSort AI incorporates ethics and responsible governance at every stage of the pipeline:
                </p>

                <div style={{ display: 'flex', flexDirection: 'column', gap: '0.85rem' }}>
                  {pillars.map((pillar, idx) => {
                    const Icon = pillar.icon;
                    return (
                      <motion.div
                        key={idx}
                        initial={{ opacity: 0, x: -10 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: idx * 0.07, type: 'spring', stiffness: 220, damping: 22 }}
                        className="glass-sm"
                        style={{
                          display: 'flex',
                          gap: '0.85rem',
                          alignItems: 'flex-start',
                          padding: '1rem 1.1rem',
                          borderRadius: 'var(--radius-md)',
                        }}
                      >
                        <div style={{
                          background: pillar.bg,
                          padding: '0.5rem',
                          borderRadius: '9px',
                          display: 'flex',
                          alignItems: 'center',
                          justifyContent: 'center',
                          flexShrink: 0,
                        }}>
                          <Icon size={19} color={pillar.color} />
                        </div>
                        <div>
                          <h4 style={{ fontSize: '0.9rem', color: 'var(--color-forest)', marginBottom: '0.2rem', fontWeight: 700 }}>
                            {pillar.title}
                          </h4>
                          <p style={{ fontSize: '0.82rem', color: 'var(--color-charcoal)', margin: 0, lineHeight: 1.55 }}>
                            {pillar.text}
                          </p>
                        </div>
                      </motion.div>
                    );
                  })}
                </div>

                <div style={{ marginTop: '1.75rem', textAlign: 'right' }}>
                  <motion.button
                    onClick={onClose}
                    className="btn-primary"
                    style={{ padding: '0.65rem 1.75rem', fontSize: '0.9rem' }}
                    whileTap={{ scale: 0.96, transition: springSnappy }}
                  >
                    Got It
                  </motion.button>
                </div>
              </div>
            </motion.div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
}
